services:

    node-cli:
        container_name: ${APP_NAME}-node-cli
        build:
            context: docker
            dockerfile: node-cli/Dockerfile
        volumes:
            - ./project:/project
        networks:
            - tg-bot-network
        depends_on:
            - php-fpm
            - php-cli

    nginx:
        restart: always
        container_name: ${APP_NAME}-nginx
        build:
            context: docker
            dockerfile: nginx/Dockerfile
        ports:
            - "8023:80"
        volumes:
            - ./project:/project
        networks:
            - tg-bot-network

    php-fpm:
        container_name: ${APP_NAME}-php-fpm
        build:
            context: docker
            dockerfile: php-fpm/Dockerfile
        volumes:
            - ./project:/project
        networks:
            - tg-bot-network

    php-cli:
        container_name: ${APP_NAME}-php-cli
        build:
            context: docker
            dockerfile: php-cli/Dockerfile
        volumes:
            - ./project:/project
        networks:
            - tg-bot-network

#    maria-db:
#        restart: always
#        image: mariadb:11.8.2
#        container_name: ${APP_NAME}-maria-db
#        volumes:
#            - ./volumes/database/mysql://var/lib/mysql
#        ports:
#            - "3323:3306"
#        command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
#        environment:
#            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#            - MYSQL_USER=${MYSQL_USER}
#            - MYSQL_DATABASE=${MYSQL_DATABASE}
#            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
#        networks:
#            - tg-bot-network

networks:
    tg-bot-network:
        external: true